version: '0.1'
services:
  api:
    build:
      context: ./
      dockerfile: local.Dockerfile
    volumes:
      - ./carriergot2:/app
    working_dir: /app
    command: sh run.sh
    environment:
      DB_HOST: db
      DB_PASS: root
      DB_DB: project
      DB_PORT: 3306
      AUTH_URL: "https://dev-apps.blumesolutions.com/jwt/decrypt"
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    ports:
      - 3300:3306
    volumes:
      - ./db:/var/lib/mysql